title: Gazi A. Raihan
email: raihan.mech157@gmail.com
description: Fluid dynamics and aerospace enthusiasts
baseurl: ""
url: "https://graihan57.github.io"
author:
  name: Gazi A. Raihan
  picture: /assets/images/bio.jpg

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
