# Welcome to Jekyll!

lang: en-US
title: Gazi A. Raihan
email: raihan.mech157@gmail.com
description: CFD and Aerodynamics Enthusiasts 
baseurl: ""
url: "https://graihan57.github.io"

author:
  name: Gazi A. Raihan
  twitter: 
  picture: /images/bio.jpg

twitter_username: graihan57
github_username: graihan57
linkedin_username: graihan57

logo: "/images/k.svg"

search: false
search_full_content: false
search_provider: lunr

algolia:
  application_id: 
  index_name: 
  search_only_api_key: 
  powered_by: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

feed:
  path: atom.xml

# Pagination
paginate: 10
paginate_path: /page:num/

exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs
  - /example

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      read_time: true
